import type { Facility } from "./types";

export const BANGALORE_FACILITIES: Facility[] = [
  // Hospitals
  { id: "blr-manipal-old-airport", name: "Manipal Hospital, Old Airport Road", type: "hospital", city: "Bangalore", address: "HAL Airport Road, Bengaluru", latitude: 12.9587, longitude: 77.6494 },
  { id: "blr-manipal-malleshwaram", name: "Manipal Hospital, Malleshwaram", type: "hospital", city: "Bangalore", address: "Malleshwaram, Bengaluru", latitude: 13.0012, longitude: 77.5712 },
  { id: "blr-apollo-jayanagar", name: "Apollo Hospitals, Jayanagar", type: "hospital", city: "Bangalore", address: "Jayanagar, Bengaluru", latitude: 12.9312, longitude: 77.5856 },
  { id: "blr-apollo-bannerghatta", name: "Apollo Hospitals, Bannerghatta Road", type: "hospital", city: "Bangalore", address: "Bannerghatta Road, Bengaluru", latitude: 12.8912, longitude: 77.6012 },
  { id: "blr-fortis-cunningham", name: "Fortis Hospital, Cunningham Road", type: "hospital", city: "Bangalore", address: "Cunningham Road, Bengaluru", latitude: 12.9845, longitude: 77.5912 },
  { id: "blr-fortis-bannerghatta", name: "Fortis Hospital, Bannerghatta Road", type: "hospital", city: "Bangalore", address: "Bannerghatta Road, Bengaluru", latitude: 12.8789, longitude: 77.5989 },
  { id: "blr-narayana-health", name: "Narayana Health City", type: "hospital", city: "Bangalore", address: "Bommasandra, Bengaluru", latitude: 12.8123, longitude: 77.6912 },
  { id: "blr-columbia-asia", name: "Columbia Asia Referral Hospital", type: "hospital", city: "Bangalore", address: "Yeshwanthpur, Bengaluru", latitude: 13.0234, longitude: 77.5512 },
  { id: "blr-st-johns", name: "St. John's Medical College Hospital", type: "hospital", city: "Bangalore", address: "Sarjapur Road, Bengaluru", latitude: 12.9345, longitude: 77.6234 },
  { id: "blr-baptist-hospital", name: "Bangalore Baptist Hospital", type: "hospital", city: "Bangalore", address: "Hebbal, Bengaluru", latitude: 13.0456, longitude: 77.5989 },
  { id: "blr-ramaiah", name: "M.S. Ramaiah Medical College Hospital", type: "hospital", city: "Bangalore", address: "New BEL Road, Bengaluru", latitude: 13.0289, longitude: 77.5567 },
  { id: "blr-victoria", name: "Victoria Hospital", type: "hospital", city: "Bangalore", address: "Fort Road, Bengaluru", latitude: 12.9612, longitude: 77.5789 },
  { id: "blr-bowring", name: "Bowring and Lady Curzon Hospital", type: "hospital", city: "Bangalore", address: "Shivajinagar, Bengaluru", latitude: 12.9789, longitude: 77.6012 },
  { id: "blr-nimhans", name: "NIMHANS", type: "hospital", city: "Bangalore", address: "Hosur Road, Bengaluru", latitude: 12.9412, longitude: 77.5967 },
  { id: "blr-kidwai", name: "Kidwai Memorial Institute of Oncology", type: "hospital", city: "Bangalore", address: "Hosur Road, Bengaluru", latitude: 12.9389, longitude: 77.5934 },
  { id: "blr-mallya", name: "Mallya Hospital", type: "hospital", city: "Bangalore", address: "Vittal Mallya Road, Bengaluru", latitude: 12.9712, longitude: 77.5934 },
  { id: "blr-hosmat", name: "HOSMAT Hospital", type: "hospital", city: "Bangalore", address: "Magrath Road, Bengaluru", latitude: 12.9689, longitude: 77.6012 },
  { id: "blr-sakra", name: "Sakra World Hospital", type: "hospital", city: "Bangalore", address: "Devarabeesanahalli, Bengaluru", latitude: 12.9234, longitude: 77.6912 },
  { id: "blr-cloudnine", name: "Cloudnine Hospital", type: "hospital", city: "Bangalore", address: "Old Airport Road, Bengaluru", latitude: 12.9567, longitude: 77.6512 },
  { id: "blr-aster-cv-raman", name: "Aster CMI Hospital", type: "hospital", city: "Bangalore", address: "Sahakaranagar, Bengaluru", latitude: 13.0612, longitude: 77.5912 },
  { id: "blr-sparsh", name: "Sparsh Hospital", type: "hospital", city: "Bangalore", address: "Yeshwanthpur, Bengaluru", latitude: 13.0212, longitude: 77.5489 },
  { id: "blr-kgf-general", name: "KC General Hospital", type: "hospital", city: "Bangalore", address: "Malleshwaram, Bengaluru", latitude: 13.0034, longitude: 77.5734 },
  // Blood Banks
  { id: "blr-manipal-bb", name: "Manipal Hospital Blood Bank", type: "blood_bank", city: "Bangalore", address: "HAL Airport Road, Bengaluru", latitude: 12.9590, longitude: 77.6497 },
  { id: "blr-apollo-bb", name: "Apollo Hospitals Blood Bank", type: "blood_bank", city: "Bangalore", address: "Jayanagar, Bengaluru", latitude: 12.9315, longitude: 77.5859 },
  { id: "blr-fortis-bb", name: "Fortis Hospital Blood Bank", type: "blood_bank", city: "Bangalore", address: "Cunningham Road, Bengaluru", latitude: 12.9848, longitude: 77.5915 },
  { id: "blr-rotary-ttk", name: "Rotary Bangalore TTK Blood Bank", type: "blood_bank", city: "Bangalore", address: "Millers Road, Bengaluru", latitude: 12.9812, longitude: 77.5934 },
  { id: "blr-nimhans-bb", name: "NIMHANS Blood Bank", type: "blood_bank", city: "Bangalore", address: "Hosur Road, Bengaluru", latitude: 12.9415, longitude: 77.5970 },
  { id: "blr-ramaiah-bb", name: "M.S. Ramaiah Hospital Blood Bank", type: "blood_bank", city: "Bangalore", address: "New BEL Road, Bengaluru", latitude: 13.0292, longitude: 77.5570 },
  { id: "blr-mallya-bb", name: "Mallya Hospital Blood Bank", type: "blood_bank", city: "Bangalore", address: "Vittal Mallya Road, Bengaluru", latitude: 12.9715, longitude: 77.5937 },
  { id: "blr-victoria-bb", name: "Victoria Hospital Blood Bank", type: "blood_bank", city: "Bangalore", address: "Fort Road, Bengaluru", latitude: 12.9615, longitude: 77.5792 },
  { id: "blr-red-cross", name: "Karnataka Red Cross Blood Bank", type: "blood_bank", city: "Bangalore", address: "Palace Road, Bengaluru", latitude: 12.9789, longitude: 77.5845 },
  { id: "blr-lions-bb", name: "Lions Blood Bank", type: "blood_bank", city: "Bangalore", address: "Millers Road, Bengaluru", latitude: 12.9823, longitude: 77.5945 },
  { id: "blr-kims-bb", name: "KIMS Hospital Blood Bank", type: "blood_bank", city: "Bangalore", address: "Basavanagudi, Bengaluru", latitude: 12.9456, longitude: 77.5712 },
  { id: "blr-hosmat-bb", name: "HOSMAT Hospital Blood Bank", type: "blood_bank", city: "Bangalore", address: "Magrath Road, Bengaluru", latitude: 12.9692, longitude: 77.6015 },
];
