import type { Facility } from "./types";

export const DELHI_FACILITIES: Facility[] = [
  // Hospitals
  { id: "del-aiims", name: "AIIMS New Delhi", type: "hospital", city: "Delhi", address: "Ansari Nagar, New Delhi", latitude: 28.5672, longitude: 77.2100 },
  { id: "del-apollo-indraprastha", name: "Indraprastha Apollo Hospitals", type: "hospital", city: "Delhi", address: "Sarita Vihar, New Delhi", latitude: 28.5412, longitude: 77.2834 },
  { id: "del-max-saket", name: "Max Super Speciality Hospital, Saket", type: "hospital", city: "Delhi", address: "Press Enclave Road, Saket", latitude: 28.5234, longitude: 77.2123 },
  { id: "del-max-shalimar", name: "Max Super Speciality Hospital, Shalimar Bagh", type: "hospital", city: "Delhi", address: "Shalimar Bagh, New Delhi", latitude: 28.7234, longitude: 77.1567 },
  { id: "del-fortis-shalimar", name: "Fortis Hospital, Shalimar Bagh", type: "hospital", city: "Delhi", address: "Shalimar Bagh, New Delhi", latitude: 28.7212, longitude: 77.1589 },
  { id: "del-fortis-escorts", name: "Fortis Escorts Heart Institute", type: "hospital", city: "Delhi", address: "Okhla, New Delhi", latitude: 28.5234, longitude: 77.2678 },
  { id: "del-safdarjung", name: "Safdarjung Hospital", type: "hospital", city: "Delhi", address: "Ansari Nagar, New Delhi", latitude: 28.5712, longitude: 77.2089 },
  { id: "del-rml", name: "Dr. Ram Manohar Lohia Hospital", type: "hospital", city: "Delhi", address: "Connaught Place, New Delhi", latitude: 28.6345, longitude: 77.2123 },
  { id: "del-lnjp", name: "Lok Nayak Jai Prakash Narayan Hospital", type: "hospital", city: "Delhi", address: "Jawaharlal Nehru Marg, New Delhi", latitude: 28.6345, longitude: 77.2345 },
  { id: "del-ganga-ram", name: "Sir Ganga Ram Hospital", type: "hospital", city: "Delhi", address: "Rajinder Nagar, New Delhi", latitude: 28.6412, longitude: 77.1912 },
  { id: "del-blk-max", name: "BLK-Max Super Speciality Hospital", type: "hospital", city: "Delhi", address: "Pusa Road, New Delhi", latitude: 28.6412, longitude: 77.1789 },
  { id: "del-medanta", name: "Medanta - The Medicity", type: "hospital", city: "Delhi", address: "Sector 38, Gurugram", latitude: 28.4395, longitude: 77.0412 },
  { id: "del-holy-family", name: "Holy Family Hospital", type: "hospital", city: "Delhi", address: "Okhla, New Delhi", latitude: 28.5512, longitude: 77.2789 },
  { id: "del-moolchand", name: "Moolchand Medcity", type: "hospital", city: "Delhi", address: "Lajpat Nagar, New Delhi", latitude: 28.5678, longitude: 77.2345 },
  { id: "del-saket-city", name: "Max Smart Super Speciality Hospital, Saket", type: "hospital", city: "Delhi", address: "Press Enclave Road, Saket", latitude: 28.5245, longitude: 77.2134 },
  { id: "del-trauma-centre", name: "Jai Prakash Narayan Apex Trauma Centre", type: "hospital", city: "Delhi", address: "AIIMS Campus, New Delhi", latitude: 28.5689, longitude: 77.2112 },
  { id: "del-national-heart", name: "National Heart Institute", type: "hospital", city: "Delhi", address: "East of Kailash, New Delhi", latitude: 28.5512, longitude: 77.2567 },
  { id: "del-dharamshila", name: "Dharamshila Narayana Superspeciality Hospital", type: "hospital", city: "Delhi", address: "Vasundhara Enclave, New Delhi", latitude: 28.6012, longitude: 77.3234 },
  { id: "del-venkateshwar", name: "Venkateshwar Hospital", type: "hospital", city: "Delhi", address: "Dwarka, New Delhi", latitude: 28.5912, longitude: 77.0456 },
  { id: "del-psri", name: "Pushpawati Singhania Research Institute", type: "hospital", city: "Delhi", address: "Sheikh Sarai, New Delhi", latitude: 28.5345, longitude: 77.2234 },
  { id: "del-artemis-gurgaon", name: "Artemis Hospital", type: "hospital", city: "Delhi", address: "Sector 51, Gurugram", latitude: 28.4412, longitude: 77.0567 },
  { id: "del-jaipur-golden", name: "Jaipur Golden Hospital", type: "hospital", city: "Delhi", address: "Rohini, New Delhi", latitude: 28.7234, longitude: 77.1234 },
  // Blood Banks
  { id: "del-aiims-bb", name: "AIIMS Blood Centre", type: "blood_bank", city: "Delhi", address: "Ansari Nagar, New Delhi", latitude: 28.5675, longitude: 77.2103 },
  { id: "del-apollo-bb", name: "Indraprastha Apollo Hospitals Blood Bank", type: "blood_bank", city: "Delhi", address: "Sarita Vihar, New Delhi", latitude: 28.5415, longitude: 77.2837 },
  { id: "del-max-saket-bb", name: "Max Hospital Saket Blood Bank", type: "blood_bank", city: "Delhi", address: "Saket, New Delhi", latitude: 28.5237, longitude: 77.2126 },
  { id: "del-max-shalimar-bb", name: "Max Hospital Shalimar Bagh Blood Bank", type: "blood_bank", city: "Delhi", address: "Shalimar Bagh, New Delhi", latitude: 28.7237, longitude: 77.1570 },
  { id: "del-fortis-shalimar-bb", name: "Fortis Hospital Shalimar Bagh Blood Bank", type: "blood_bank", city: "Delhi", address: "Shalimar Bagh, New Delhi", latitude: 28.7215, longitude: 77.1592 },
  { id: "del-fortis-escorts-bb", name: "Fortis Escorts Heart Institute Blood Bank", type: "blood_bank", city: "Delhi", address: "Okhla, New Delhi", latitude: 28.5237, longitude: 77.2681 },
  { id: "del-safdarjung-bb", name: "Safdarjung Hospital Blood Bank", type: "blood_bank", city: "Delhi", address: "Ansari Nagar, New Delhi", latitude: 28.5715, longitude: 77.2092 },
  { id: "del-ganga-ram-bb", name: "Sir Ganga Ram Hospital Blood Bank", type: "blood_bank", city: "Delhi", address: "Rajinder Nagar, New Delhi", latitude: 28.6415, longitude: 77.1915 },
  { id: "del-red-cross", name: "Indian Red Cross Society Blood Bank Delhi", type: "blood_bank", city: "Delhi", address: "Red Cross Road, New Delhi", latitude: 28.6234, longitude: 77.2123 },
  { id: "del-rotary-bb", name: "Rotary Blood Bank Delhi", type: "blood_bank", city: "Delhi", address: "Tughlakabad, New Delhi", latitude: 28.5012, longitude: 77.2567 },
  { id: "del-trauma-bb", name: "JPNA Trauma Centre Blood Bank", type: "blood_bank", city: "Delhi", address: "AIIMS Campus, New Delhi", latitude: 28.5692, longitude: 77.2115 },
  { id: "del-national-heart-bb", name: "National Heart Institute Blood Bank", type: "blood_bank", city: "Delhi", address: "East of Kailash, New Delhi", latitude: 28.5515, longitude: 77.2570 },
];
