import type { Facility } from "./types";

export const MUMBAI_FACILITIES: Facility[] = [
  // Hospitals
  { id: "mum-tata-memorial", name: "Tata Memorial Hospital", type: "hospital", city: "Mumbai", address: "Dr. E Borges Road, Parel", latitude: 19.0047, longitude: 72.8428 },
  { id: "mum-lilavati", name: "Lilavati Hospital", type: "hospital", city: "Mumbai", address: "Bandra Reclamation, Bandra West", latitude: 19.0512, longitude: 72.8345 },
  { id: "mum-kokilaben", name: "Kokilaben Dhirubhai Ambani Hospital", type: "hospital", city: "Mumbai", address: "Lokhandwala, Andheri West", latitude: 19.1345, longitude: 72.8234 },
  { id: "mum-apollo-navi", name: "Apollo Hospitals, Navi Mumbai", type: "hospital", city: "Mumbai", address: "Belapur, Navi Mumbai", latitude: 19.0234, longitude: 73.0345 },
  { id: "mum-apollo-mumbai", name: "Apollo Hospitals, Mumbai", type: "hospital", city: "Mumbai", address: "Tardeo, Mumbai", latitude: 18.9712, longitude: 72.8123 },
  { id: "mum-fortis-mulund", name: "Fortis Hospital, Mulund", type: "hospital", city: "Mumbai", address: "Mulund Goregaon Link Road, Bhandup", latitude: 19.1712, longitude: 72.9567 },
  { id: "mum-fortis-kalyan", name: "Fortis Hospital, Kalyan", type: "hospital", city: "Mumbai", address: "Kalyan, Thane", latitude: 19.2456, longitude: 73.1345 },
  { id: "mum-hn-reliance", name: "Sir H. N. Reliance Foundation Hospital", type: "hospital", city: "Mumbai", address: "Girgaon, Mumbai", latitude: 18.9567, longitude: 72.8123 },
  { id: "mum-jaslok", name: "Jaslok Hospital", type: "hospital", city: "Mumbai", address: "Pedder Road, Mumbai", latitude: 18.9712, longitude: 72.8012 },
  { id: "mum-nanavati", name: "Nanavati Super Speciality Hospital", type: "hospital", city: "Mumbai", address: "Vile Parle West, Mumbai", latitude: 19.0912, longitude: 72.8456 },
  { id: "mum-breach-candy", name: "Breach Candy Hospital", type: "hospital", city: "Mumbai", address: "Breach Candy, Mumbai", latitude: 18.9712, longitude: 72.8012 },
  { id: "mum-hinduja", name: "P. D. Hinduja Hospital", type: "hospital", city: "Mumbai", address: "Mahim, Mumbai", latitude: 19.0345, longitude: 72.8456 },
  { id: "mum-global", name: "Global Hospital, Parel", type: "hospital", city: "Mumbai", address: "Parel, Mumbai", latitude: 19.0012, longitude: 72.8456 },
  { id: "mum-sl-raheja", name: "S.L. Raheja Hospital", type: "hospital", city: "Mumbai", address: "Mahim, Mumbai", latitude: 19.0389, longitude: 72.8412 },
  { id: "mum-asian-heart", name: "Asian Heart Institute", type: "hospital", city: "Mumbai", address: "Bandra Kurla Complex, Mumbai", latitude: 19.0678, longitude: 72.8678 },
  { id: "mum-jj-hospital", name: "JJ Hospital", type: "hospital", city: "Mumbai", address: "Byculla, Mumbai", latitude: 18.9712, longitude: 72.8345 },
  { id: "mum-kem-hospital", name: "KEM Hospital", type: "hospital", city: "Mumbai", address: "Parel, Mumbai", latitude: 19.0012, longitude: 72.8412 },
  { id: "mum-sion-hospital", name: "Lokmanya Tilak Municipal General Hospital (Sion)", type: "hospital", city: "Mumbai", address: "Sion, Mumbai", latitude: 19.0456, longitude: 72.8678 },
  { id: "mum-holy-family", name: "Holy Family Hospital", type: "hospital", city: "Mumbai", address: "Bandra West, Mumbai", latitude: 19.0567, longitude: 72.8234 },
  { id: "mum-wockhardt", name: "Wockhardt Hospital", type: "hospital", city: "Mumbai", address: "Mumbai Central, Mumbai", latitude: 18.9712, longitude: 72.8234 },
  { id: "mum-hiranandani", name: "Hiranandani Hospital", type: "hospital", city: "Mumbai", address: "Powai, Mumbai", latitude: 19.1189, longitude: 72.9067 },
  { id: "mum-jupiter-thane", name: "Jupiter Hospital, Thane", type: "hospital", city: "Mumbai", address: "Thane West", latitude: 19.2123, longitude: 72.9789 },
  // Blood Banks
  { id: "mum-tata-memorial-bb", name: "Tata Memorial Hospital Blood Bank", type: "blood_bank", city: "Mumbai", address: "Parel, Mumbai", latitude: 19.0050, longitude: 72.8431 },
  { id: "mum-lilavati-bb", name: "Lilavati Hospital Blood Bank", type: "blood_bank", city: "Mumbai", address: "Bandra Reclamation, Mumbai", latitude: 19.0515, longitude: 72.8348 },
  { id: "mum-kokilaben-bb", name: "Kokilaben Hospital Blood Bank", type: "blood_bank", city: "Mumbai", address: "Andheri West, Mumbai", latitude: 19.1348, longitude: 72.8237 },
  { id: "mum-fortis-mulund-bb", name: "Fortis Hospital Blood Bank, Mulund", type: "blood_bank", city: "Mumbai", address: "Bhandup, Mumbai", latitude: 19.1715, longitude: 72.9570 },
  { id: "mum-jj-bb", name: "JJ Hospital Blood Bank", type: "blood_bank", city: "Mumbai", address: "Byculla, Mumbai", latitude: 18.9715, longitude: 72.8348 },
  { id: "mum-kem-bb", name: "KEM Hospital Blood Bank", type: "blood_bank", city: "Mumbai", address: "Parel, Mumbai", latitude: 19.0015, longitude: 72.8415 },
  { id: "mum-asian-heart-bb", name: "Asian Heart Institute Blood Bank", type: "blood_bank", city: "Mumbai", address: "BKC, Mumbai", latitude: 19.0681, longitude: 72.8681 },
  { id: "mum-holy-family-bb", name: "Holy Family Hospital Blood Bank", type: "blood_bank", city: "Mumbai", address: "Bandra West, Mumbai", latitude: 19.0570, longitude: 72.8237 },
  { id: "mum-nanavati-bb", name: "Nanavati Hospital Blood Bank", type: "blood_bank", city: "Mumbai", address: "Vile Parle, Mumbai", latitude: 19.0915, longitude: 72.8459 },
  { id: "mum-jaslok-bb", name: "Jaslok Hospital Blood Bank", type: "blood_bank", city: "Mumbai", address: "Pedder Road, Mumbai", latitude: 18.9715, longitude: 72.8015 },
  { id: "mum-red-cross", name: "Indian Red Cross Society Blood Bank Mumbai", type: "blood_bank", city: "Mumbai", address: "Fort, Mumbai", latitude: 18.9345, longitude: 72.8345 },
  { id: "mum-actrec-bb", name: "ACTREC Blood Bank", type: "blood_bank", city: "Mumbai", address: "Kharghar, Navi Mumbai", latitude: 19.0345, longitude: 73.0678 },
];
