-- Facilities catalog (seeded from app data) and custom hospital location fields

CREATE TABLE IF NOT EXISTS facilities (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  type TEXT NOT NULL CHECK (type IN ('hospital', 'blood_bank')),
  city TEXT NOT NULL,
  address TEXT NOT NULL,
  latitude DOUBLE PRECISION NOT NULL,
  longitude DOUBLE PRECISION NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_facilities_city ON facilities(city);
CREATE INDEX IF NOT EXISTS idx_facilities_type ON facilities(type);
CREATE INDEX IF NOT EXISTS idx_facilities_name ON facilities(name);

ALTER TABLE blood_requests
  ADD COLUMN IF NOT EXISTS facility_id TEXT REFERENCES facilities(id),
  ADD COLUMN IF NOT EXISTS custom_hospital_name TEXT,
  ADD COLUMN IF NOT EXISTS pincode TEXT,
  ADD COLUMN IF NOT EXISTS location_district TEXT,
  ADD COLUMN IF NOT EXISTS location_state TEXT;

INSERT INTO facilities (id, name, type, city, address, latitude, longitude) VALUES
  ('palakkad-district-hospital', 'District Hospital Palakkad', 'hospital', 'Palakkad', 'Sultanpet, Palakkad', 10.7867, 76.6548),
  ('palakkad-mannarkkad-thq', 'Taluk Headquarters Hospital Mannarkkad', 'hospital', 'Palakkad', 'Mannarkkad, Palakkad', 10.9923, 76.4589),
  ('palakkad-ahalia-hospital', 'Ahalia Diabetes Hospital', 'hospital', 'Palakkad', 'Kozhipara, Palakkad', 10.8012, 76.7123),
  ('palakkad-ahalia-blood-bank', 'Ahalia Blood Bank', 'blood_bank', 'Palakkad', 'Kozhipara, Palakkad', 10.8015, 76.7126),
  ('palakkad-karuna-medical', 'Karuna Medical College Hospital', 'hospital', 'Palakkad', 'Vilayodi, Chittur, Palakkad', 10.7012, 76.7345),
  ('palakkad-valluvanad-hospital', 'Valluvanad Hospital', 'hospital', 'Palakkad', 'Kanniyampuram, Ottapalam', 10.7723, 76.3789),
  ('palakkad-valluvanad-blood-bank', 'Valluvanad Hospital Blood Bank', 'blood_bank', 'Palakkad', 'Kanniyampuram, Ottapalam', 10.7726, 76.3792),
  ('palakkad-blood-bank', 'Palakkad Blood Bank', 'blood_bank', 'Palakkad', 'Civil Station Road, Palakkad', 10.7845, 76.6512),
  ('palakkad-co-op-hospital', 'Palakkad District Co-operative Hospital', 'hospital', 'Palakkad', 'Kallekkad, Kodunthirapully, Palakkad', 10.7789, 76.6456),
  ('palakkad-pk-das-ims', 'PK Das Institute of Medical Sciences', 'hospital', 'Palakkad', 'Vaniamkulam, Ottapalam', 10.7456, 76.4012),
  ('palakkad-kerala-medical-college', 'Kerala Medical College Hospital', 'hospital', 'Palakkad', 'Mangode, Cherpulassery', 10.8234, 76.5123),
  ('palakkad-mother-care', 'Mother Care Hospital', 'hospital', 'Palakkad', 'Vattambalam, Mannarkkad', 10.9876, 76.4523),
  ('palakkad-esi-hospital', 'ESI Hospital Palakkad', 'hospital', 'Palakkad', 'Palakkad', 10.789, 76.6589),
  ('palakkad-mercy-hospital', 'Mercy College Hospital', 'hospital', 'Palakkad', 'Palakkad', 10.7823, 76.6498),
  ('palakkad-metna-hospital', 'Metna Hospital', 'hospital', 'Palakkad', 'Palakkad', 10.7912, 76.6612),
  ('palakkad-ottapalam-govt', 'Government Hospital Ottapalam', 'hospital', 'Palakkad', 'Ottapalam, Palakkad', 10.7712, 76.3845),
  ('palakkad-chittur-govt', 'Government Hospital Chittur', 'hospital', 'Palakkad', 'Chittur, Palakkad', 10.7012, 76.7234),
  ('cbe-psg-hospital', 'PSG Hospitals', 'hospital', 'Coimbatore', 'Peelamedu, Coimbatore', 11.0286, 76.9103),
  ('cbe-kovai-medical', 'Kovai Medical Center & Hospital', 'hospital', 'Coimbatore', 'Avinashi Road, Coimbatore', 11.0245, 76.9662),
  ('cbe-ganga-hospital', 'Ganga Hospital', 'hospital', 'Coimbatore', 'Mettupalayam Road, Coimbatore', 11.0352, 76.9361),
  ('cbe-sri-ramakrishna', 'Sri Ramakrishna Hospital', 'hospital', 'Coimbatore', 'Siddhapudur, Coimbatore', 11.0089, 76.9668),
  ('cbe-kg-hospital', 'KG Hospital', 'hospital', 'Coimbatore', 'Govt Arts College Road, Coimbatore', 11.0012, 76.9662),
  ('cbe-gem-hospital', 'GEM Hospital & Research Centre', 'hospital', 'Coimbatore', 'Ramanathapuram, Coimbatore', 11.0054, 76.9789),
  ('cbe-royal-care', 'Royal Care Super Speciality Hospital', 'hospital', 'Coimbatore', 'Neelambur, Coimbatore', 11.0621, 77.0432),
  ('cbe-kongunad-hospital', 'Kongunad Hospital', 'hospital', 'Coimbatore', 'Tatabad, Coimbatore', 11.0168, 76.9558),
  ('cbe-sakthi-hospital', 'Sakthi Hospital', 'hospital', 'Coimbatore', 'Gandhipuram, Coimbatore', 11.0183, 76.9687),
  ('cbe-medical-college', 'Coimbatore Medical College Hospital', 'hospital', 'Coimbatore', 'Avinashi Road, Coimbatore', 11.0123, 76.9812),
  ('cbe-abirami-hospital', 'Abirami Hospital', 'hospital', 'Coimbatore', 'Sundarapuram, Coimbatore', 10.9789, 76.9456),
  ('cbe-ashwin-hospital', 'Ashwin Hospital', 'hospital', 'Coimbatore', 'R.S. Puram, Coimbatore', 11.0089, 76.9512),
  ('cbe-viswabharathi', 'Viswabharathi Medical College Hospital', 'hospital', 'Coimbatore', 'Kunnathurmedu, Coimbatore', 11.0234, 76.9234),
  ('cbe-esi-hospital', 'ESI Hospital Coimbatore', 'hospital', 'Coimbatore', 'Avinashi Road, Coimbatore', 11.0198, 76.9723),
  ('cbe-sri-nehru-maternity', 'Sri Nehru Maternity & Child Care Hospital', 'hospital', 'Coimbatore', 'Gandhipuram, Coimbatore', 11.0178, 76.9678),
  ('cbe-ramana-gounder', 'Ramana Gounder Medical Trust Hospital', 'hospital', 'Coimbatore', 'Thudiyalur, Coimbatore', 11.0789, 76.9123),
  ('cbe-kmch', 'KMCH - Kovai Medical Center Hospital', 'hospital', 'Coimbatore', 'Trichy Road, Coimbatore', 11.0012, 76.9898),
  ('cbe-pollachi-govt', 'Government Hospital Pollachi', 'hospital', 'Coimbatore', 'Pollachi Main Road', 10.6574, 77.0103),
  ('cbe-nurani-phc', 'Nurani Primary Health Centre', 'hospital', 'Coimbatore', 'Nurani, Pollachi Taluk', 10.6489, 77.0234),
  ('cbe-kg-blood-bank', 'KG Hospital Regional Blood Bank', 'blood_bank', 'Coimbatore', 'Govt Arts College Road, Coimbatore', 11.0015, 76.9665),
  ('cbe-psg-blood-bank', 'PSG Hospitals Blood Bank', 'blood_bank', 'Coimbatore', 'Peelamedu, Coimbatore', 11.0289, 76.9108),
  ('cbe-sri-ramakrishna-bb', 'Sri Ramakrishna Hospital Blood Bank', 'blood_bank', 'Coimbatore', 'Siddhapudur, Coimbatore', 11.0092, 76.9671),
  ('cbe-ganga-blood-bank', 'Ganga Hospital Blood Centre', 'blood_bank', 'Coimbatore', 'Mettupalayam Road, Coimbatore', 11.0355, 76.9364),
  ('cbe-royal-care-bb', 'Royal Care Hospitals Blood Centre', 'blood_bank', 'Coimbatore', 'Neelambur, Coimbatore', 11.0624, 77.0435),
  ('cbe-imc-blood-bank', 'IMC Blood Bank', 'blood_bank', 'Coimbatore', 'Gandhipuram, Coimbatore', 11.0178, 76.9695),
  ('cbe-red-cross', 'Indian Red Cross Society Blood Bank', 'blood_bank', 'Coimbatore', 'Race Course, Coimbatore', 11.0089, 76.9712),
  ('cbe-govt-blood-bank', 'Government Hospital Blood Bank', 'blood_bank', 'Coimbatore', 'Coimbatore GH, Coimbatore', 11.0125, 76.9815),
  ('cbe-pollachi-blood-bank', 'Pollachi Government Blood Bank', 'blood_bank', 'Coimbatore', 'Government Hospital, Pollachi', 10.6578, 77.0108),
  ('kochi-amrita-aims', 'Amrita Institute of Medical Sciences (AIMS)', 'hospital', 'Kochi', 'Ponekkara, Edapally, Kochi', 10.033, 76.355),
  ('kochi-aster-medcity', 'Aster Medcity', 'hospital', 'Kochi', 'Cheranelloor, Kochi', 10.0512, 76.3123),
  ('kochi-govt-medical-college', 'Government Medical College Hospital', 'hospital', 'Kochi', 'HMT Colony, Kalamassery', 10.0512, 76.3234),
  ('kochi-general-hospital', 'General Hospital Ernakulam', 'hospital', 'Kochi', 'Marine Drive, Ernakulam', 9.9689, 76.2789),
  ('kochi-lakeshore', 'Lakeshore Hospital & Research Centre', 'hospital', 'Kochi', 'NH-47 Bypass, Maradu', 9.9312, 76.3234),
  ('kochi-renai-medicity', 'Renai Medicity', 'hospital', 'Kochi', 'Palarivattom, Kochi', 10.0012, 76.3123),
  ('kochi-medical-trust', 'Medical Trust Hospital', 'hospital', 'Kochi', 'MG Road, Ernakulam', 9.9678, 76.2845),
  ('kochi-kims-health', 'KIMS Health Hospital', 'hospital', 'Kochi', 'Anayara, Kochi', 8.9789, 76.9123),
  ('kochi-lisie-hospital', 'Lisie Hospital', 'hospital', 'Kochi', 'Kaloor, Ernakulam', 9.9912, 76.2912),
  ('kochi-lourdes-hospital', 'Lourdes Hospital', 'hospital', 'Kochi', 'Pachalam, Ernakulam', 9.9845, 76.2956),
  ('kochi-rajagiri-hospital', 'Rajagiri Hospital', 'hospital', 'Kochi', 'Chunangamveli, Aluva', 10.1012, 76.3567),
  ('kochi-sunrise-hospital', 'Sunrise Institute of Medical Sciences', 'hospital', 'Kochi', 'Seaport-Airport Road, Kakkanad', 10.0123, 76.3456),
  ('kochi-vps-lakeshore', 'VPS Lakeshore Hospital', 'hospital', 'Kochi', 'Nettoor, Maradu', 9.9289, 76.3189),
  ('kochi-pvs-memorial', 'PVS Memorial Hospital', 'hospital', 'Kochi', 'Kaloor, Kochi', 9.9934, 76.2889),
  ('kochi-little-flower', 'Little Flower Hospital', 'hospital', 'Kochi', 'Angamaly, Ernakulam', 10.1912, 76.3789),
  ('kochi-indira-gandhi-co-op', 'Indira Gandhi Co-operative Hospital', 'hospital', 'Kochi', 'Gandhi Nagar, Kochi', 9.9612, 76.2912),
  ('kochi-specialist-hospital', 'Specialist Hospital Ernakulam', 'hospital', 'Kochi', 'North, Ernakulam', 9.9789, 76.2823),
  ('kochi-ernakulam-medical', 'Ernakulam Medical Centre', 'hospital', 'Kochi', 'Palarivattom, Kochi', 10.0034, 76.3089),
  ('kochi-amrita-blood-bank', 'Amrita Hospital Blood Bank', 'blood_bank', 'Kochi', 'Ponekkara, Edapally', 10.0333, 76.3553),
  ('kochi-gmch-blood-bank', 'Government Medical College Blood Bank', 'blood_bank', 'Kochi', 'Kalamassery', 10.0515, 76.3237),
  ('kochi-general-hospital-bb', 'General Hospital Ernakulam Blood Centre', 'blood_bank', 'Kochi', 'Marine Drive, Ernakulam', 9.9692, 76.2792),
  ('kochi-aster-blood-bank', 'Aster Medcity Blood Bank', 'blood_bank', 'Kochi', 'Cheranelloor, Kochi', 10.0515, 76.3126),
  ('kochi-lakeshore-bb', 'Lakeshore Hospital Blood Bank', 'blood_bank', 'Kochi', 'Maradu, Kochi', 9.9315, 76.3237),
  ('kochi-renai-blood-bank', 'Renai Medicity Blood Bank', 'blood_bank', 'Kochi', 'Palarivattom, Kochi', 10.0015, 76.3126),
  ('kochi-medical-trust-bb', 'Medical Trust Hospital Blood Bank', 'blood_bank', 'Kochi', 'MG Road, Ernakulam', 9.9681, 76.2848),
  ('kochi-ima-blood-bank', 'IMA Voluntary Donor Blood Bank', 'blood_bank', 'Kochi', 'TD Road, Ernakulam', 9.9712, 76.2812),
  ('kochi-lourdes-bb', 'Lourdes Hospital Blood Bank', 'blood_bank', 'Kochi', 'Pachalam, Ernakulam', 9.9848, 76.2959),
  ('kochi-red-cross', 'Indian Red Cross Society Blood Bank Kochi', 'blood_bank', 'Kochi', 'Ernakulam', 9.9701, 76.2834),
  ('chennai-apollo-greams', 'Apollo Hospitals, Greams Road', 'hospital', 'Chennai', 'Greams Lane, Greams Road', 13.0604, 80.2496),
  ('chennai-apollo-teynampet', 'Apollo Specialty Hospital, Teynampet', 'hospital', 'Chennai', 'Anna Salai, Teynampet', 13.0412, 80.2456),
  ('chennai-apollo-omr', 'Apollo Specialty Hospital, OMR', 'hospital', 'Chennai', 'Old Mahabalipuram Road, Perungudi', 12.9656, 80.2456),
  ('chennai-apollo-vanagaram', 'Apollo Specialty Hospital, Vanagaram', 'hospital', 'Chennai', 'Vanagaram-Ambattur Main Road', 13.0789, 80.1234),
  ('chennai-apollo-kilpauk', 'Apollo First Med Hospitals, Kilpauk', 'hospital', 'Chennai', 'Poonamallee High Road, Kilpauk', 13.0789, 80.2345),
  ('chennai-apollo-proton', 'Apollo Proton Cancer Centre', 'hospital', 'Chennai', 'Taramani, Chennai', 13.0123, 80.2456),
  ('chennai-fortis-malar', 'Fortis Malar Hospital', 'hospital', 'Chennai', 'Gandhi Nagar, Adyar', 13.0067, 80.2546),
  ('chennai-fortis-vadapalani', 'Fortis Hospital Vadapalani', 'hospital', 'Chennai', 'Vadapalani, Chennai', 13.0512, 80.2123),
  ('chennai-miot', 'MIOT International', 'hospital', 'Chennai', 'Manapakkam, Chennai', 13.0189, 80.1623),
  ('chennai-sri-ramachandra', 'Sri Ramachandra Medical Centre', 'hospital', 'Chennai', 'Porur, Chennai', 13.0356, 80.1567),
  ('chennai-mgm-healthcare', 'MGM Healthcare', 'hospital', 'Chennai', 'Nelson Manickam Road, Aminjikarai', 13.0712, 80.2234),
  ('chennai-kauvery', 'Kauvery Hospital', 'hospital', 'Chennai', 'Radial Road, Alwarpet', 13.0345, 80.2567),
  ('chennai-madras-medical-mission', 'Madras Medical Mission', 'hospital', 'Chennai', 'Mogappair, Chennai', 13.0789, 80.1789),
  ('chennai-gleneagles', 'Gleneagles Global Health City', 'hospital', 'Chennai', 'Perumbakkam, Chennai', 12.9123, 80.2123),
  ('chennai-sims', 'SIMS Hospital', 'hospital', 'Chennai', 'Vadapalani, Chennai', 13.0523, 80.2134),
  ('chennai-vijaya-hospital', 'Vijaya Hospital', 'hospital', 'Chennai', 'Vadapalani, Chennai', 13.0534, 80.2145),
  ('chennai-billroth', 'Billroth Hospitals', 'hospital', 'Chennai', 'Raja Annamalaipuram, Chennai', 13.0234, 80.2678),
  ('chennai-chettinad', 'Chettinad Super Speciality Hospital', 'hospital', 'Chennai', 'Rajiv Gandhi Salai, Kelambakkam', 12.8012, 80.2234),
  ('chennai-rajiv-gandhi-gh', 'Rajiv Gandhi Government General Hospital', 'hospital', 'Chennai', 'Park Town, Chennai', 13.0827, 80.2707),
  ('chennai-stanley', 'Government Stanley Medical College Hospital', 'hospital', 'Chennai', 'Royapuram, Chennai', 13.1045, 80.2891),
  ('chennai-kilpauk-medical', 'Kilpauk Medical College Hospital', 'hospital', 'Chennai', 'Poonamallee High Road, Kilpauk', 13.0812, 80.2312),
  ('chennai-omandurar', 'Omandurar Government Estate Hospital', 'hospital', 'Chennai', 'Anna Salai, Chennai', 13.0678, 80.2678),
  ('chennai-apollo-bb', 'Apollo Hospitals Blood Bank', 'blood_bank', 'Chennai', 'Greams Road, Chennai', 13.0608, 80.2501),
  ('chennai-red-cross', 'Indian Red Cross Society Blood Bank', 'blood_bank', 'Chennai', 'Montieth Road, Chennai', 13.0734, 80.2601),
  ('chennai-lifeline-bb', 'Lifeline Blood Bank', 'blood_bank', 'Chennai', 'Kilpauk, Chennai', 13.0789, 80.2345),
  ('chennai-miot-bb', 'MIOT International Blood Bank', 'blood_bank', 'Chennai', 'Manapakkam, Chennai', 13.0192, 80.1626),
  ('chennai-sri-ramachandra-bb', 'Sri Ramachandra Blood Bank', 'blood_bank', 'Chennai', 'Porur, Chennai', 13.0359, 80.157),
  ('chennai-mgm-bb', 'MGM Healthcare Blood Bank', 'blood_bank', 'Chennai', 'Aminjikarai, Chennai', 13.0715, 80.2237),
  ('chennai-govt-general-bb', 'Rajiv Gandhi GH Blood Bank', 'blood_bank', 'Chennai', 'Park Town, Chennai', 13.083, 80.271),
  ('chennai-stanley-bb', 'Stanley Hospital Blood Bank', 'blood_bank', 'Chennai', 'Royapuram, Chennai', 13.1048, 80.2894),
  ('chennai-rotary-bb', 'Rotary Blood Bank Chennai', 'blood_bank', 'Chennai', 'T Nagar, Chennai', 13.0412, 80.2345),
  ('chennai-jeevan-bb', 'Jeevan Blood Bank and Research Centre', 'blood_bank', 'Chennai', 'Royapettah, Chennai', 13.0512, 80.2678),
  ('blr-manipal-old-airport', 'Manipal Hospital, Old Airport Road', 'hospital', 'Bangalore', 'HAL Airport Road, Bengaluru', 12.9587, 77.6494),
  ('blr-manipal-malleshwaram', 'Manipal Hospital, Malleshwaram', 'hospital', 'Bangalore', 'Malleshwaram, Bengaluru', 13.0012, 77.5712),
  ('blr-apollo-jayanagar', 'Apollo Hospitals, Jayanagar', 'hospital', 'Bangalore', 'Jayanagar, Bengaluru', 12.9312, 77.5856),
  ('blr-apollo-bannerghatta', 'Apollo Hospitals, Bannerghatta Road', 'hospital', 'Bangalore', 'Bannerghatta Road, Bengaluru', 12.8912, 77.6012),
  ('blr-fortis-cunningham', 'Fortis Hospital, Cunningham Road', 'hospital', 'Bangalore', 'Cunningham Road, Bengaluru', 12.9845, 77.5912),
  ('blr-fortis-bannerghatta', 'Fortis Hospital, Bannerghatta Road', 'hospital', 'Bangalore', 'Bannerghatta Road, Bengaluru', 12.8789, 77.5989),
  ('blr-narayana-health', 'Narayana Health City', 'hospital', 'Bangalore', 'Bommasandra, Bengaluru', 12.8123, 77.6912),
  ('blr-columbia-asia', 'Columbia Asia Referral Hospital', 'hospital', 'Bangalore', 'Yeshwanthpur, Bengaluru', 13.0234, 77.5512),
  ('blr-st-johns', 'St. John''s Medical College Hospital', 'hospital', 'Bangalore', 'Sarjapur Road, Bengaluru', 12.9345, 77.6234),
  ('blr-baptist-hospital', 'Bangalore Baptist Hospital', 'hospital', 'Bangalore', 'Hebbal, Bengaluru', 13.0456, 77.5989),
  ('blr-ramaiah', 'M.S. Ramaiah Medical College Hospital', 'hospital', 'Bangalore', 'New BEL Road, Bengaluru', 13.0289, 77.5567),
  ('blr-victoria', 'Victoria Hospital', 'hospital', 'Bangalore', 'Fort Road, Bengaluru', 12.9612, 77.5789),
  ('blr-bowring', 'Bowring and Lady Curzon Hospital', 'hospital', 'Bangalore', 'Shivajinagar, Bengaluru', 12.9789, 77.6012),
  ('blr-nimhans', 'NIMHANS', 'hospital', 'Bangalore', 'Hosur Road, Bengaluru', 12.9412, 77.5967),
  ('blr-kidwai', 'Kidwai Memorial Institute of Oncology', 'hospital', 'Bangalore', 'Hosur Road, Bengaluru', 12.9389, 77.5934),
  ('blr-mallya', 'Mallya Hospital', 'hospital', 'Bangalore', 'Vittal Mallya Road, Bengaluru', 12.9712, 77.5934),
  ('blr-hosmat', 'HOSMAT Hospital', 'hospital', 'Bangalore', 'Magrath Road, Bengaluru', 12.9689, 77.6012),
  ('blr-sakra', 'Sakra World Hospital', 'hospital', 'Bangalore', 'Devarabeesanahalli, Bengaluru', 12.9234, 77.6912),
  ('blr-cloudnine', 'Cloudnine Hospital', 'hospital', 'Bangalore', 'Old Airport Road, Bengaluru', 12.9567, 77.6512),
  ('blr-aster-cv-raman', 'Aster CMI Hospital', 'hospital', 'Bangalore', 'Sahakaranagar, Bengaluru', 13.0612, 77.5912),
  ('blr-sparsh', 'Sparsh Hospital', 'hospital', 'Bangalore', 'Yeshwanthpur, Bengaluru', 13.0212, 77.5489),
  ('blr-kgf-general', 'KC General Hospital', 'hospital', 'Bangalore', 'Malleshwaram, Bengaluru', 13.0034, 77.5734),
  ('blr-manipal-bb', 'Manipal Hospital Blood Bank', 'blood_bank', 'Bangalore', 'HAL Airport Road, Bengaluru', 12.959, 77.6497),
  ('blr-apollo-bb', 'Apollo Hospitals Blood Bank', 'blood_bank', 'Bangalore', 'Jayanagar, Bengaluru', 12.9315, 77.5859),
  ('blr-fortis-bb', 'Fortis Hospital Blood Bank', 'blood_bank', 'Bangalore', 'Cunningham Road, Bengaluru', 12.9848, 77.5915),
  ('blr-rotary-ttk', 'Rotary Bangalore TTK Blood Bank', 'blood_bank', 'Bangalore', 'Millers Road, Bengaluru', 12.9812, 77.5934),
  ('blr-nimhans-bb', 'NIMHANS Blood Bank', 'blood_bank', 'Bangalore', 'Hosur Road, Bengaluru', 12.9415, 77.597),
  ('blr-ramaiah-bb', 'M.S. Ramaiah Hospital Blood Bank', 'blood_bank', 'Bangalore', 'New BEL Road, Bengaluru', 13.0292, 77.557),
  ('blr-mallya-bb', 'Mallya Hospital Blood Bank', 'blood_bank', 'Bangalore', 'Vittal Mallya Road, Bengaluru', 12.9715, 77.5937),
  ('blr-victoria-bb', 'Victoria Hospital Blood Bank', 'blood_bank', 'Bangalore', 'Fort Road, Bengaluru', 12.9615, 77.5792),
  ('blr-red-cross', 'Karnataka Red Cross Blood Bank', 'blood_bank', 'Bangalore', 'Palace Road, Bengaluru', 12.9789, 77.5845),
  ('blr-lions-bb', 'Lions Blood Bank', 'blood_bank', 'Bangalore', 'Millers Road, Bengaluru', 12.9823, 77.5945),
  ('blr-kims-bb', 'KIMS Hospital Blood Bank', 'blood_bank', 'Bangalore', 'Basavanagudi, Bengaluru', 12.9456, 77.5712),
  ('blr-hosmat-bb', 'HOSMAT Hospital Blood Bank', 'blood_bank', 'Bangalore', 'Magrath Road, Bengaluru', 12.9692, 77.6015),
  ('mum-tata-memorial', 'Tata Memorial Hospital', 'hospital', 'Mumbai', 'Dr. E Borges Road, Parel', 19.0047, 72.8428),
  ('mum-lilavati', 'Lilavati Hospital', 'hospital', 'Mumbai', 'Bandra Reclamation, Bandra West', 19.0512, 72.8345),
  ('mum-kokilaben', 'Kokilaben Dhirubhai Ambani Hospital', 'hospital', 'Mumbai', 'Lokhandwala, Andheri West', 19.1345, 72.8234),
  ('mum-apollo-navi', 'Apollo Hospitals, Navi Mumbai', 'hospital', 'Mumbai', 'Belapur, Navi Mumbai', 19.0234, 73.0345),
  ('mum-apollo-mumbai', 'Apollo Hospitals, Mumbai', 'hospital', 'Mumbai', 'Tardeo, Mumbai', 18.9712, 72.8123),
  ('mum-fortis-mulund', 'Fortis Hospital, Mulund', 'hospital', 'Mumbai', 'Mulund Goregaon Link Road, Bhandup', 19.1712, 72.9567),
  ('mum-fortis-kalyan', 'Fortis Hospital, Kalyan', 'hospital', 'Mumbai', 'Kalyan, Thane', 19.2456, 73.1345),
  ('mum-hn-reliance', 'Sir H. N. Reliance Foundation Hospital', 'hospital', 'Mumbai', 'Girgaon, Mumbai', 18.9567, 72.8123),
  ('mum-jaslok', 'Jaslok Hospital', 'hospital', 'Mumbai', 'Pedder Road, Mumbai', 18.9712, 72.8012),
  ('mum-nanavati', 'Nanavati Super Speciality Hospital', 'hospital', 'Mumbai', 'Vile Parle West, Mumbai', 19.0912, 72.8456),
  ('mum-breach-candy', 'Breach Candy Hospital', 'hospital', 'Mumbai', 'Breach Candy, Mumbai', 18.9712, 72.8012),
  ('mum-hinduja', 'P. D. Hinduja Hospital', 'hospital', 'Mumbai', 'Mahim, Mumbai', 19.0345, 72.8456),
  ('mum-global', 'Global Hospital, Parel', 'hospital', 'Mumbai', 'Parel, Mumbai', 19.0012, 72.8456),
  ('mum-sl-raheja', 'S.L. Raheja Hospital', 'hospital', 'Mumbai', 'Mahim, Mumbai', 19.0389, 72.8412),
  ('mum-asian-heart', 'Asian Heart Institute', 'hospital', 'Mumbai', 'Bandra Kurla Complex, Mumbai', 19.0678, 72.8678),
  ('mum-jj-hospital', 'JJ Hospital', 'hospital', 'Mumbai', 'Byculla, Mumbai', 18.9712, 72.8345),
  ('mum-kem-hospital', 'KEM Hospital', 'hospital', 'Mumbai', 'Parel, Mumbai', 19.0012, 72.8412),
  ('mum-sion-hospital', 'Lokmanya Tilak Municipal General Hospital (Sion)', 'hospital', 'Mumbai', 'Sion, Mumbai', 19.0456, 72.8678),
  ('mum-holy-family', 'Holy Family Hospital', 'hospital', 'Mumbai', 'Bandra West, Mumbai', 19.0567, 72.8234),
  ('mum-wockhardt', 'Wockhardt Hospital', 'hospital', 'Mumbai', 'Mumbai Central, Mumbai', 18.9712, 72.8234),
  ('mum-hiranandani', 'Hiranandani Hospital', 'hospital', 'Mumbai', 'Powai, Mumbai', 19.1189, 72.9067),
  ('mum-jupiter-thane', 'Jupiter Hospital, Thane', 'hospital', 'Mumbai', 'Thane West', 19.2123, 72.9789),
  ('mum-tata-memorial-bb', 'Tata Memorial Hospital Blood Bank', 'blood_bank', 'Mumbai', 'Parel, Mumbai', 19.005, 72.8431),
  ('mum-lilavati-bb', 'Lilavati Hospital Blood Bank', 'blood_bank', 'Mumbai', 'Bandra Reclamation, Mumbai', 19.0515, 72.8348),
  ('mum-kokilaben-bb', 'Kokilaben Hospital Blood Bank', 'blood_bank', 'Mumbai', 'Andheri West, Mumbai', 19.1348, 72.8237),
  ('mum-fortis-mulund-bb', 'Fortis Hospital Blood Bank, Mulund', 'blood_bank', 'Mumbai', 'Bhandup, Mumbai', 19.1715, 72.957),
  ('mum-jj-bb', 'JJ Hospital Blood Bank', 'blood_bank', 'Mumbai', 'Byculla, Mumbai', 18.9715, 72.8348),
  ('mum-kem-bb', 'KEM Hospital Blood Bank', 'blood_bank', 'Mumbai', 'Parel, Mumbai', 19.0015, 72.8415),
  ('mum-asian-heart-bb', 'Asian Heart Institute Blood Bank', 'blood_bank', 'Mumbai', 'BKC, Mumbai', 19.0681, 72.8681),
  ('mum-holy-family-bb', 'Holy Family Hospital Blood Bank', 'blood_bank', 'Mumbai', 'Bandra West, Mumbai', 19.057, 72.8237),
  ('mum-nanavati-bb', 'Nanavati Hospital Blood Bank', 'blood_bank', 'Mumbai', 'Vile Parle, Mumbai', 19.0915, 72.8459),
  ('mum-jaslok-bb', 'Jaslok Hospital Blood Bank', 'blood_bank', 'Mumbai', 'Pedder Road, Mumbai', 18.9715, 72.8015),
  ('mum-red-cross', 'Indian Red Cross Society Blood Bank Mumbai', 'blood_bank', 'Mumbai', 'Fort, Mumbai', 18.9345, 72.8345),
  ('mum-actrec-bb', 'ACTREC Blood Bank', 'blood_bank', 'Mumbai', 'Kharghar, Navi Mumbai', 19.0345, 73.0678),
  ('pune-ruby-hall', 'Ruby Hall Clinic', 'hospital', 'Pune', 'Sassoon Road, Pune', 18.5254, 73.8756),
  ('pune-jehangir', 'Jehangir Hospital', 'hospital', 'Pune', 'Sassoon Road, Pune', 18.5245, 73.8745),
  ('pune-sahyadri-deccan', 'Sahyadri Super Speciality Hospital, Deccan', 'hospital', 'Pune', 'Karve Road, Deccan Gymkhana', 18.5123, 73.8345),
  ('pune-sahyadri-hinjawadi', 'Sahyadri Hospital, Hinjawadi', 'hospital', 'Pune', 'Hinjawadi, Pune', 18.5912, 73.7412),
  ('pune-sahyadri-wanowrie', 'Sahyadri Hospital, Wanowrie', 'hospital', 'Pune', 'Wanowrie, Pune', 18.4912, 73.9012),
  ('pune-kem-pune', 'KEM Hospital Pune', 'hospital', 'Pune', 'Rasta Peth, Pune', 18.5189, 73.8712),
  ('pune-deenanath-mangeshkar', 'Deenanath Mangeshkar Hospital', 'hospital', 'Pune', 'Erandwane, Pune', 18.5012, 73.8234),
  ('pune-apollo', 'Apollo Hospitals, Pune', 'hospital', 'Pune', 'Bavdhan, Pune', 18.5234, 73.7789),
  ('pune-aditya-birla', 'Aditya Birla Memorial Hospital', 'hospital', 'Pune', 'Chinchwad, Pune', 18.6234, 73.8012),
  ('pune-columbia-asia', 'Columbia Asia Hospital, Pune', 'hospital', 'Pune', 'Kharadi, Pune', 18.5512, 73.9456),
  ('pune-noble', 'Noble Hospital', 'hospital', 'Pune', 'Hadapsar, Pune', 18.5012, 73.9345),
  ('pune-inlaks-budhrani', 'Inlaks Budhrani Hospital', 'hospital', 'Pune', 'Koregaon Park, Pune', 18.5345, 73.8912),
  ('pune-poona-hospital', 'Poona Hospital and Research Centre', 'hospital', 'Pune', 'Sadashiv Peth, Pune', 18.5089, 73.8512),
  ('pune-bharati-vidyapeeth', 'Bharati Vidyapeeth Medical College Hospital', 'hospital', 'Pune', 'Dhankawadi, Pune', 18.4612, 73.8567),
  ('pune-symbiosis', 'Symbiosis University Hospital', 'hospital', 'Pune', 'Lavale, Pune', 18.5234, 73.6789),
  ('pune-rahat-hospital', 'Rahat Hospital', 'hospital', 'Pune', 'Camp, Pune', 18.5123, 73.8789),
  ('pune-sasoon-govt', 'Sassoon General Hospital', 'hospital', 'Pune', 'Sassoon Road, Pune', 18.5267, 73.8767),
  ('pune-ycm-hospital', 'YCM Hospital Pimpri', 'hospital', 'Pune', 'Pimpri, Pune', 18.6234, 73.8123),
  ('pune-ruby-hall-bb', 'Ruby Hall Clinic Blood Centre', 'blood_bank', 'Pune', 'Sassoon Road, Pune', 18.5257, 73.8759),
  ('pune-jehangir-bb', 'Jehangir Hospital Blood Centre', 'blood_bank', 'Pune', 'Sassoon Road, Pune', 18.5248, 73.8748),
  ('pune-sahyadri-bb', 'Sahyadri Hospital Blood Bank', 'blood_bank', 'Pune', 'Deccan, Pune', 18.5126, 73.8348),
  ('pune-deenanath-bb', 'Deenanath Mangeshkar Hospital Blood Bank', 'blood_bank', 'Pune', 'Erandwane, Pune', 18.5015, 73.8237),
  ('pune-sasoon-bb', 'Sassoon General Hospital Blood Bank', 'blood_bank', 'Pune', 'Sassoon Road, Pune', 18.527, 73.877),
  ('pune-apollo-bb', 'Apollo Hospitals Blood Bank Pune', 'blood_bank', 'Pune', 'Bavdhan, Pune', 18.5237, 73.7792),
  ('pune-poona-bb', 'Poona Hospital Blood Bank', 'blood_bank', 'Pune', 'Sadashiv Peth, Pune', 18.5092, 73.8515),
  ('pune-red-cross', 'Indian Red Cross Society Blood Bank Pune', 'blood_bank', 'Pune', 'Camp, Pune', 18.5145, 73.8812),
  ('pune-bharati-bb', 'Bharati Hospital Blood Bank', 'blood_bank', 'Pune', 'Dhankawadi, Pune', 18.4615, 73.857),
  ('del-aiims', 'AIIMS New Delhi', 'hospital', 'Delhi', 'Ansari Nagar, New Delhi', 28.5672, 77.21),
  ('del-apollo-indraprastha', 'Indraprastha Apollo Hospitals', 'hospital', 'Delhi', 'Sarita Vihar, New Delhi', 28.5412, 77.2834),
  ('del-max-saket', 'Max Super Speciality Hospital, Saket', 'hospital', 'Delhi', 'Press Enclave Road, Saket', 28.5234, 77.2123),
  ('del-max-shalimar', 'Max Super Speciality Hospital, Shalimar Bagh', 'hospital', 'Delhi', 'Shalimar Bagh, New Delhi', 28.7234, 77.1567),
  ('del-fortis-shalimar', 'Fortis Hospital, Shalimar Bagh', 'hospital', 'Delhi', 'Shalimar Bagh, New Delhi', 28.7212, 77.1589),
  ('del-fortis-escorts', 'Fortis Escorts Heart Institute', 'hospital', 'Delhi', 'Okhla, New Delhi', 28.5234, 77.2678),
  ('del-safdarjung', 'Safdarjung Hospital', 'hospital', 'Delhi', 'Ansari Nagar, New Delhi', 28.5712, 77.2089),
  ('del-rml', 'Dr. Ram Manohar Lohia Hospital', 'hospital', 'Delhi', 'Connaught Place, New Delhi', 28.6345, 77.2123),
  ('del-lnjp', 'Lok Nayak Jai Prakash Narayan Hospital', 'hospital', 'Delhi', 'Jawaharlal Nehru Marg, New Delhi', 28.6345, 77.2345),
  ('del-ganga-ram', 'Sir Ganga Ram Hospital', 'hospital', 'Delhi', 'Rajinder Nagar, New Delhi', 28.6412, 77.1912),
  ('del-blk-max', 'BLK-Max Super Speciality Hospital', 'hospital', 'Delhi', 'Pusa Road, New Delhi', 28.6412, 77.1789),
  ('del-medanta', 'Medanta - The Medicity', 'hospital', 'Delhi', 'Sector 38, Gurugram', 28.4395, 77.0412),
  ('del-holy-family', 'Holy Family Hospital', 'hospital', 'Delhi', 'Okhla, New Delhi', 28.5512, 77.2789),
  ('del-moolchand', 'Moolchand Medcity', 'hospital', 'Delhi', 'Lajpat Nagar, New Delhi', 28.5678, 77.2345),
  ('del-saket-city', 'Max Smart Super Speciality Hospital, Saket', 'hospital', 'Delhi', 'Press Enclave Road, Saket', 28.5245, 77.2134),
  ('del-trauma-centre', 'Jai Prakash Narayan Apex Trauma Centre', 'hospital', 'Delhi', 'AIIMS Campus, New Delhi', 28.5689, 77.2112),
  ('del-national-heart', 'National Heart Institute', 'hospital', 'Delhi', 'East of Kailash, New Delhi', 28.5512, 77.2567),
  ('del-dharamshila', 'Dharamshila Narayana Superspeciality Hospital', 'hospital', 'Delhi', 'Vasundhara Enclave, New Delhi', 28.6012, 77.3234),
  ('del-venkateshwar', 'Venkateshwar Hospital', 'hospital', 'Delhi', 'Dwarka, New Delhi', 28.5912, 77.0456),
  ('del-psri', 'Pushpawati Singhania Research Institute', 'hospital', 'Delhi', 'Sheikh Sarai, New Delhi', 28.5345, 77.2234),
  ('del-artemis-gurgaon', 'Artemis Hospital', 'hospital', 'Delhi', 'Sector 51, Gurugram', 28.4412, 77.0567),
  ('del-jaipur-golden', 'Jaipur Golden Hospital', 'hospital', 'Delhi', 'Rohini, New Delhi', 28.7234, 77.1234),
  ('del-aiims-bb', 'AIIMS Blood Centre', 'blood_bank', 'Delhi', 'Ansari Nagar, New Delhi', 28.5675, 77.2103),
  ('del-apollo-bb', 'Indraprastha Apollo Hospitals Blood Bank', 'blood_bank', 'Delhi', 'Sarita Vihar, New Delhi', 28.5415, 77.2837),
  ('del-max-saket-bb', 'Max Hospital Saket Blood Bank', 'blood_bank', 'Delhi', 'Saket, New Delhi', 28.5237, 77.2126),
  ('del-max-shalimar-bb', 'Max Hospital Shalimar Bagh Blood Bank', 'blood_bank', 'Delhi', 'Shalimar Bagh, New Delhi', 28.7237, 77.157),
  ('del-fortis-shalimar-bb', 'Fortis Hospital Shalimar Bagh Blood Bank', 'blood_bank', 'Delhi', 'Shalimar Bagh, New Delhi', 28.7215, 77.1592),
  ('del-fortis-escorts-bb', 'Fortis Escorts Heart Institute Blood Bank', 'blood_bank', 'Delhi', 'Okhla, New Delhi', 28.5237, 77.2681),
  ('del-safdarjung-bb', 'Safdarjung Hospital Blood Bank', 'blood_bank', 'Delhi', 'Ansari Nagar, New Delhi', 28.5715, 77.2092),
  ('del-ganga-ram-bb', 'Sir Ganga Ram Hospital Blood Bank', 'blood_bank', 'Delhi', 'Rajinder Nagar, New Delhi', 28.6415, 77.1915),
  ('del-red-cross', 'Indian Red Cross Society Blood Bank Delhi', 'blood_bank', 'Delhi', 'Red Cross Road, New Delhi', 28.6234, 77.2123),
  ('del-rotary-bb', 'Rotary Blood Bank Delhi', 'blood_bank', 'Delhi', 'Tughlakabad, New Delhi', 28.5012, 77.2567),
  ('del-trauma-bb', 'JPNA Trauma Centre Blood Bank', 'blood_bank', 'Delhi', 'AIIMS Campus, New Delhi', 28.5692, 77.2115),
  ('del-national-heart-bb', 'National Heart Institute Blood Bank', 'blood_bank', 'Delhi', 'East of Kailash, New Delhi', 28.5515, 77.257)
ON CONFLICT (id) DO NOTHING;
